name: Publish Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: src/DLP_Win/DLP_Win
        run: dotnet restore

      - name: Build
        working-directory: src/DLP_Win/DLP_Win
        run: dotnet build --configuration Release
      
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          release_name: Release ${{ steps.previoustag.outputs.tag }}
          draft: false
          prerelease: false
          
      - name: Create Zip Archive
        run: |
          mkdir src/DLP_Win/DLP_Win/bin/Release/DLP_Win
          Copy-Item -Path src/DLP_Win/DLP_Win/bin/Release/net5.0-windows/* -Destination src/DLP_Win/DLP_Win/bin/Release/DLP_Win
          Compress-Archive -Path src/DLP_Win/DLP_Win/bin/Release/DLP_Win -DestinationPath src/DLP_Win/DLP_Win/bin/Release/DLP_Win.zip
        shell: powershell
        env:
          DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/DLP_Win/DLP_Win/bin/Release/DLP_Win.zip
          asset_name: DLP_Win.zip
          asset_content_type: application/zip
